### PR TITLE
Fix watch command on windows

### PR DESCRIPTION
**Pull request by angguss**
Fix watch command unable to find ivy executable on windows platform due to file extension

### CODE REVIEW

**Comment by dmulholland** [comment]
Fixed in the `2.0.0` release. Thanks :)

**Comment by RodrigoLeiteF** [comment]
Is there any reason you took this code instead of merging the pull request?

**Comment by dmulholland** [comment]
Took what code?

**Comment by aronson** [comment]
You essentially did a roundabout re-write of the contributed code in this pull request in commits a28b232abb2ba60d96cebeb340370297ec91cbb3 and 125336ff3bc4824ad507ff442fe406f1ab296335.

There is no attribution to the original author. You close every single pull request made, without including nor amending the commit -- which is ridiculously easy. You don't even need to use the original commit, just rebase on top of it.

It appears you want the commit history of this project to contain code committed exclusively by you. While each minor change that you incorporate is arguably inconsequential, when we look at the big picture it tells a different story. You are taking others' insights and suggestions and using them to create a project that appears to be entirely your own on the surface.

Please attribute your code, even if you don't have to explicitly do so according to your license. Playing dumb is silly. We can see the commits.

**Comment by aronson** [comment]
May I remind you that according to your own contribution policy in the repo,

> I won't merge them and, as a matter of policy, _I won't even read any of the code they contain._ (Sorry, consequence of some odd new trolling trend on GitHub.)

You clearly read the code for both the pull requests I've called you out on.

**Pull request closed without merging**
